// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtWcg4Kq6KU2GY1iCKYZiiwNzqhgH3oao',
    appId: '1:774791345895:web:33b25dbf425a45515e5442',
    messagingSenderId: '774791345895',
    projectId: 'reddittutorial-a5ce0',
    authDomain: 'reddittutorial-a5ce0.firebaseapp.com',
    storageBucket: 'reddittutorial-a5ce0.appspot.com',
    measurementId: 'G-HBGQ3L8XJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNnyX12frbVib7fSWJN7u-xA20bSe208',
    appId: '1:774791345895:android:423d6db2db2168765e5442',
    messagingSenderId: '774791345895',
    projectId: 'reddittutorial-a5ce0',
    storageBucket: 'reddittutorial-a5ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB28M-yB05aBt7_6bxlEEUD2sYmErF_73Y',
    appId: '1:774791345895:ios:bd951a32ce2832275e5442',
    messagingSenderId: '774791345895',
    projectId: 'reddittutorial-a5ce0',
    storageBucket: 'reddittutorial-a5ce0.appspot.com',
    iosClientId: '774791345895-u764p4qk7ha8pgh4hmeft1jm9p81fe7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
